// Native CPU test: fake device only, no graphics/game/Wine process.
#define STATIC_SHADOW_GPU_TEST
#include "test_static_shadow_fake_d3d.h"
#include "static_shadow_gpu.h"
#include <cassert>
#include <iostream>
#include <limits>
namespace StaticShadow {
void transformBounds(const Placement& p,Vec3 l,Vec3 h,Vec3& lo,Vec3& hi){lo={1e30f,1e30f,1e30f};hi={-1e30f,-1e30f,-1e30f};for(unsigned i=0;i<8;++i){float q[]={i&1?h.x:l.x,i&2?h.y:l.y,i&4?h.z:l.z},r[]={p.translation.x,p.translation.y,p.translation.z};for(unsigned a=0;a<3;++a)for(unsigned b=0;b<3;++b)r[a]+=p.matrix[a*3+b]*q[b];lo.x=std::min(lo.x,r[0]);lo.y=std::min(lo.y,r[1]);lo.z=std::min(lo.z,r[2]);hi.x=std::max(hi.x,r[0]);hi.y=std::max(hi.y,r[1]);hi.z=std::max(hi.z,r[2]);}}
}
using namespace StaticShadow;
std::shared_ptr<Model> model(const std::string& key){auto m=std::make_shared<Model>();m->key=key;m->contentRevision=key[0];m->vertices={{0,0,.5f,0,0},{.2f,0,.5f,1,0},{0,.2f,.5f,0,1}};m->indices={0,1,2};m->index16=true;m->batches={{0,3,0,{0,0,.5f},{.2f,.2f,.5f}}};NorthlightGI::WorldMaterial mat;mat.width=mat.height=1;mat.rgba={255,255,255,255};m->materials={mat};m->materialKeys={1};return m;}
std::shared_ptr<Snapshot> snapshot(const std::shared_ptr<Model>& m,unsigned count=2){auto s=std::make_shared<Snapshot>();s->map="test";s->mapGeneration=1;s->models[m->key]=m;for(unsigned i=0;i<count;++i){Placement p;p.uid=i;p.category=1;p.modelKey=m->key;p.low={0,0,.5f};p.high={.2f,.2f,.5f};s->placements.push_back(p);}return s;}
int main(){float matrix[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};
 {IDirect3DDevice9 d;GpuCache::Limits limits;limits.uploadBytes=20;limits.uploadMs=100;GpuCache gpu(limits);auto m=model("one"),m2=model("two");auto s=snapshot(m);uint64_t empty=0;
 for(unsigned frame=1;frame<=8;++frame){assert(gpu.update(&d,s,frame));assert(gpu.stats().frameBytes<=20);if(frame==1)empty=gpu.signature(matrix);}
 assert(gpu.stats().readyModels==1);assert(gpu.coverage(0,1,"one"));assert(gpu.signature(matrix)!=empty);assert(d.indexBuffers==1&&d.textures==1);assert(gpu.draw(&d,matrix));assert(gpu.stats().drawCalls==1&&gpu.stats().instances==2);assert(d.frequencies[0]==1&&d.frequencies[1]==1);
 auto ready=gpu.signature(matrix);const auto bytes=gpu.stats().uploadedBytes;auto moved=std::make_shared<Snapshot>(*s);gpu.update(&d,moved,20);assert(gpu.stats().uploadedBytes==bytes&&gpu.signature(matrix)==ready);
 auto extended=std::make_shared<Snapshot>(*s);extended->models[m2->key]=m2;Placement far=s->placements.front();far.modelKey=m2->key;far.uid=3;far.translation={50,0,0};far.low={50,0,.5f};far.high={50.2f,.2f,.5f};extended->placements.push_back(far);
 d.failAllocation=true;assert(!gpu.update(&d,extended,21));assert(gpu.coverage(0,1,"one")&&gpu.signature(matrix)==ready);d.failAllocation=false;
 for(unsigned frame=82;frame<90;++frame)gpu.update(&d,extended,frame);assert(gpu.stats().readyModels==2);assert(d.textures==1);assert(gpu.signature(matrix)==ready); // distant publication does not invalidate this cascade
 d.failInstance=true;assert(gpu.draw(&d,matrix));assert(gpu.stats().drawCalls==2);assert(d.frequencies[0]==1&&d.frequencies[1]==1);
 auto newMap=std::make_shared<Snapshot>();newMap->map="other";newMap->mapGeneration=2;gpu.update(&d,newMap,91);assert(gpu.stats().readyModels==0&&!gpu.coverage(0,1,"one"));gpu.reset();assert(FakeResource::alive==0);
 }
 {IDirect3DDevice9 d;d.maxStreams=1;GpuCache gpu;auto s=snapshot(model("fallback"),3);gpu.update(&d,s,1);gpu.update(&d,s,2);assert(gpu.draw(&d,matrix));assert(gpu.stats().drawCalls==3&&!gpu.stats().instancing);gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;GpuCache gpu;gpu.setAdmission([](size_t){return false;});gpu.update(&d,snapshot(model("refused")),1);assert(gpu.stats().readyModels==0&&d.indexBuffers==0);gpu.reset();assert(FakeResource::alive==0);}

 {IDirect3DDevice9 d;GpuCache gpu;auto old=model("same");auto initial=snapshot(old);gpu.update(&d,initial,1);const auto signature=gpu.signature(matrix);auto newer=model("same");newer->contentRevision+=1;auto next=snapshot(newer);d.failAllocation=true;assert(!gpu.update(&d,next,2));assert(!gpu.coverage(next->placements[0],newer->contentRevision));assert(gpu.signature(matrix)==signature);assert(gpu.draw(&d,matrix));d.failAllocation=false;gpu.update(&d,next,62);assert(gpu.coverage(next->placements[0],newer->contentRevision));assert(gpu.signature(matrix)!=signature);auto moved=next->placements[0];moved.translation.x=1;assert(!gpu.coverage(moved,newer->contentRevision));gpu.update(&d,next,63);assert(gpu.stats().readyModels==1);gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;GpuCache gpu;auto a=model("alphaA"),b=model("alphaB");b->materials[0].rgba[3]=100;b->materialKeys=a->materialKeys;auto s=snapshot(a);s->models[b->key]=b;auto p=s->placements[0];p.modelKey=b->key;p.uid=10;s->placements.push_back(p);gpu.update(&d,s,1);gpu.update(&d,s,2);assert(d.textures==2);d.failInstancedDraw=true;assert(gpu.draw(&d,matrix));assert(gpu.stats().drawCalls==3);assert(d.frequencies[0]==1&&d.frequencies[1]==1);gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;GpuCache::Limits limits;limits.residentBytes=100;GpuCache gpu(limits);auto a=snapshot(model("evictA"));gpu.update(&d,a,1);assert(gpu.stats().readyModels==1);auto b=snapshot(model("evictB"));gpu.update(&d,b,2);assert(gpu.coverage(0,1,"evictB"));assert(gpu.stats().evictions==1&&gpu.stats().residentBytes<=100);gpu.reset();assert(FakeResource::alive==0);}

 {IDirect3DDevice9 d;GpuCache gpu;auto s=snapshot(model("owner"));gpu.update(&d,s,1);const auto baseline=gpu.signature(matrix);gpu.setCoveredPlacements({s->placements[0]});const auto excluded=gpu.signature(matrix);assert(excluded!=baseline&&!gpu.coverage(s->placements[0],s->models.begin()->second->contentRevision));assert(gpu.coverage(s->placements[1],s->models.begin()->second->contentRevision));assert(gpu.draw(&d,matrix)&&gpu.stats().instances==1);gpu.setCoveredPlacements({s->placements[0],s->placements[0]});assert(gpu.signature(matrix)==excluded);auto mismatch=s->placements[0];mismatch.matrix[0]=2;gpu.setCoveredPlacements({mismatch});assert(gpu.signature(matrix)==baseline&&gpu.coverage(s->placements[0],s->models.begin()->second->contentRevision));gpu.setCoveredPlacements({});assert(gpu.signature(matrix)==baseline);assert(gpu.draw(&d,matrix)&&gpu.stats().instances==2);gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;GpuCache gpu;auto old=snapshot(model("idleOld"));gpu.update(&d,old,1);assert(gpu.stats().readyModels==1);auto next=snapshot(model("idleNew"));auto uploaded=gpu.stats().uploadedBytes;gpu.update(&d,next,2000,false);assert(gpu.stats().readyModels==0&&gpu.stats().residentBytes==0&&gpu.stats().uploadedBytes==uploaded&&gpu.stats().frameBytes==0);gpu.update(&d,next,2001,true);assert(gpu.coverage(next->placements[0],next->models.begin()->second->contentRevision));gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;GpuCache gpu;auto s=snapshot(model("upstream"),1);auto up=s->placements[0];up.uid=8;up.translation.z=-2;s->placements.push_back(up);auto far=up;far.uid=9;far.translation.z=2;s->placements.push_back(far);gpu.update(&d,s,1);assert(gpu.draw(&d,matrix));assert(gpu.stats().instances==2);gpu.reset();assert(FakeResource::alive==0);}

 {IDirect3DDevice9 d;GpuCache gpu;auto empty=std::make_shared<Snapshot>();empty->map="empty";empty->mapGeneration=1;gpu.update(&d,empty,1);assert(gpu.draw(&d,matrix)&&FakeResource::alive==0);gpu.reset();}
 // A fully warm cache does not even visit a model/material map per frame.
 {IDirect3DDevice9 d;GpuCache gpu;auto s=snapshot(model("warm"));gpu.update(&d,s,1);const auto visits=gpu.stats().maintenanceVisits,bytes=gpu.stats().uploadedBytes,publications=gpu.stats().publications;for(unsigned f=2;f<10002;++f){gpu.update(&d,s,f);assert(gpu.stats().pendingModels==0&&gpu.stats().readyModels==1&&gpu.stats().frameBytes==0);}assert(gpu.stats().maintenanceVisits==visits&&gpu.stats().uploadedBytes==bytes&&gpu.stats().publications==publications);gpu.reset();assert(FakeResource::alive==0);}
 // Expire exactly after the last wanted update, including idle maintenance.
 {IDirect3DDevice9 d;GpuCache::Limits l;l.retainFrames=3;GpuCache gpu(l);auto s=snapshot(model("expiry"));gpu.update(&d,s,1);gpu.update(&d,s,100);auto empty=std::make_shared<Snapshot>();empty->map=s->map;empty->mapGeneration=1;gpu.update(&d,empty,101,false);const auto visits=gpu.stats().maintenanceVisits;gpu.update(&d,empty,103,false);assert(gpu.stats().readyModels==1&&gpu.stats().maintenanceVisits==visits);gpu.update(&d,empty,104,false);assert(gpu.stats().readyModels==0&&gpu.stats().residentBytes==0);gpu.reset();assert(FakeResource::alive==0);}
 // Never upload canceled missing work, and count pending without map rescans.
 {IDirect3DDevice9 d;GpuCache gpu;auto s=snapshot(model("cancel"));gpu.update(&d,s,1,false);assert(gpu.stats().pendingModels==1);const auto visits=gpu.stats().maintenanceVisits;gpu.update(&d,s,2,false);assert(gpu.stats().maintenanceVisits==visits);auto empty=std::make_shared<Snapshot>();empty->map=s->map;empty->mapGeneration=1;gpu.update(&d,empty,3);assert(gpu.stats().pendingModels==0&&d.indexBuffers==0);gpu.reset();assert(FakeResource::alive==0);}
 // Mixed safe/near-crossing placements MUST use separate shader variants.
 for(bool opaque:{false,true}){IDirect3DDevice9 d;GpuCache gpu;auto m=model("paths");if(opaque)m->materials[0].alphaCutoff=0;auto s=snapshot(m,1);auto near=s->placements[0];near.uid=2;near.translation.z=-1;s->placements.push_back(near);gpu.update(&d,s,1);assert(gpu.draw(&d,matrix));assert(gpu.stats().instances==2);assert(d.pixelDraws[opaque?2:1]==1&&d.pixelDraws[opaque?3:0]==1);gpu.reset();assert(FakeResource::alive==0);}
 {IDirect3DDevice9 d;d.failOptionalShaders=true;GpuCache gpu;auto s=snapshot(model("shaderfallback"));gpu.update(&d,s,1);assert(gpu.draw(&d,matrix));assert(d.pixelDraws[0]==1&&d.pixelDraws[1]==0);gpu.reset();assert(FakeResource::alive==0);}
 // Exact content/order across append ranges, wrap and consecutive cascades.
 auto streamScene=[&](unsigned batches){auto m=model("stream");m->batches.resize(batches,m->batches.front());auto s=snapshot(m,700);for(unsigned i=0;i<s->placements.size();++i){auto& p=s->placements[i];p.translation.x=i*.0001f;p.matrix[0]=1+i*.0001f;}return s;};
 auto checkTransforms=[](const IDirect3DDevice9& d,const Snapshot& s,unsigned batches){assert(d.drawnTransforms.size()==s.placements.size()*batches);size_t n=0;for(unsigned b=0;b<batches;++b)for(const auto& p:s.placements){const auto& actual=d.drawnTransforms[n++];for(unsigned r=0;r<3;++r){for(unsigned c=0;c<3;++c)assert(actual[r*4+c]==p.matrix[r*3+c]);assert(actual[r*4+3]==(r==0?p.translation.x:r==1?p.translation.y:p.translation.z));}}};
 {IDirect3DDevice9 d;d.captureTransforms=true;GpuCache gpu;auto s=streamScene(41);NorthlightLockMeter::state().frameSite[NorthlightLockMeter::Instances].store(0);assert(gpu.update(&d,s,1));assert(d.instanceBuffer->bytes.size()==8192*48);assert(gpu.draw(&d,matrix));assert(gpu.draw(&d,matrix));checkTransforms(d,*s,82);
  unsigned end=0,discards=0;for(const auto& lock:d.instanceBuffer->locks){assert(lock.bytes<=8192*48);if(lock.flags==D3DLOCK_DISCARD){assert(lock.offset==0);if(discards)assert(end+lock.bytes>d.instanceBuffer->bytes.size());++discards;}else{assert(lock.flags==D3DLOCK_NOOVERWRITE&&lock.offset==end);}end=lock.offset+lock.bytes;assert(end<=d.instanceBuffer->bytes.size());}
  assert(discards>1&&discards<10);assert(gpu.stats().instanceLocks<12&&gpu.stats().instanceDiscards==discards&&gpu.stats().instanceBytes==700*82*48);assert(gpu.stats().drawCalls==123&&gpu.stats().instances==700*41);
  // 0.3.192 (DXVK3): the LOCK METER charges every instance DISCARD at the whole buffer (what DXVK 3.x charges), nothing for NOOVERWRITE appends.
  assert(NorthlightLockMeter::state().frameSite[NorthlightLockMeter::Instances].load()==uint64_t(gpu.stats().instanceDiscards)*(d.instanceBuffer->bytes.size()/48)*48);assert(d.frequencies[0]==1&&d.frequencies[1]==1&&!d.streams[1]);
  gpu.reset();assert(FakeResource::alive==0);d.drawnTransforms.clear();gpu.update(&d,s,2);assert(gpu.draw(&d,matrix));assert(d.instanceBuffer->locks.front().flags==D3DLOCK_DISCARD&&d.instanceBuffer->locks.front().offset==0);checkTransforms(d,*s,41);gpu.reset();assert(FakeResource::alive==0);
 }
 // Older offset-less devices and failed larger allocation keep the original path.
 for(unsigned mode=0;mode<2;++mode){IDirect3DDevice9 d;d.captureTransforms=true;d.streamOffsetsSupported=mode!=0;d.failLargeInstanceAllocation=mode==1;GpuCache gpu;auto s=streamScene(2);assert(gpu.update(&d,s,1));assert(d.instanceBuffer->bytes.size()==256*48);assert(gpu.draw(&d,matrix));checkTransforms(d,*s,2);for(const auto& lock:d.instanceBuffer->locks)assert(lock.offset==0&&lock.flags==D3DLOCK_DISCARD);assert(gpu.stats().drawCalls==6);gpu.reset();assert(FakeResource::alive==0);}
 // Every failure preserves all transforms through non-instanced replay, including
 // a device that advertises offsets but rejects a nonzero offset at submission.
 for(unsigned mode=0;mode<5;++mode){IDirect3DDevice9 d;d.captureTransforms=true;GpuCache gpu;auto s=streamScene(1);assert(gpu.update(&d,s,1));d.instanceBuffer->failLock=mode==0;d.instanceBuffer->failUnlock=mode==1;d.failInstanceOffset=mode==2;d.failInstance=mode==3;d.failInstancedDraw=mode==4;assert(gpu.draw(&d,matrix));checkTransforms(d,*s,1);assert(gpu.stats().instances==700&&d.frequencies[0]==1&&d.frequencies[1]==1&&!d.streams[1]);d.drawnTransforms.clear();assert(gpu.draw(&d,matrix));checkTransforms(d,*s,1);assert(gpu.stats().drawCalls==700);gpu.reset();assert(FakeResource::alive==0);}
 // Hundreds of small groups share one backing store instead of renaming it for
 // every model. Draw count, instance count, shaders and material grouping match.
 {IDirect3DDevice9 d;GpuCache::Limits limits;limits.uploadMs=1000;GpuCache gpu(limits);auto s=std::make_shared<Snapshot>();s->map="groups";s->mapGeneration=1;for(unsigned i=0;i<400;++i){auto m=model("group"+std::to_string(i));s->models[m->key]=m;for(unsigned j=0;j<2;++j){Placement p;p.modelKey=m->key;p.uid=i*2+j;s->placements.push_back(p);}}assert(gpu.update(&d,s,1));assert(gpu.stats().readyModels==400);assert(gpu.draw(&d,matrix));assert(gpu.stats().drawCalls==400&&gpu.stats().instances==800&&gpu.stats().instanceLocks==1&&gpu.stats().instanceDiscards==1);gpu.reset();assert(FakeResource::alive==0);}
 std::cout<<"static shadow GPU lifecycle/budget/alpha-sharing/cascade/fallback/upstream/append-stream tests passed\n";
}
