#!/usr/bin/env python3
"""Compile only standalone HLSL build tools in an external Wine prefix.

Does not load WoW, a game DLL, or a graphics device. The generated header and
manifest are published only after every entry passes the Shader Model 3 gate.
"""
from pathlib import Path
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
sys.path[:0] = [str(Path(__file__).resolve().parents[2]), str(Path(__file__).resolve().parents[1])]  # repo root, scripts/
import northlight_paths as fp  # noqa: E402
from build_environment import wine_build_prefix, zig_env, TOOLS, WINE_ROOT, ZIG

HERE = Path(__file__).resolve().parent   # compile_shaders.cpp and the built compile_shaders.exe
ENTRIES = (("WorldNormals", "ps_3_0"), ("WorldLighting", "ps_3_0"), ("WorldGI", "ps_3_0"), ("WorldFog", "ps_3_0"), ("FogBlur", "ps_3_0"), ("LocalDirect", "ps_3_0"), ("RemovalSmooth", "ps_3_0"), ("TemporalLight", "ps_3_0"), ("LocalFog", "ps_3_0"), ("SourceVisibilityPS", "ps_3_0"),
           ("WorldComposite", "ps_3_0"), ("ShadowVS", "vs_3_0"), ("ShadowCacheVS", "vs_3_0"),
           ("ShadowPS", "ps_3_0"), ("ShadowReplayPS", "ps_3_0"), ("ShadowUnion", "ps_3_0"))


def validate_assembly(path, target):
    """Baseline SM3 instruction slots and temporary-register limits.

    Cost references: Microsoft dx9-graphics-reference-asm-{ps,vs}-instructions-
    {ps,vs}-3-0. Only 2D texture instructions are emitted by these entries.
    """
    assembly = path.read_text()
    costs = dict.fromkeys("abs add break cmp dp3 dp4 else endif exp expp frc log logp mad max min mov mova mul nop rcp ret rsq setp sge slt sub texld".split(), 1)
    costs.update(dict.fromkeys("call crs dp2add dsx dsy endloop endrep lrp m3x2 texkill texldl".split(), 2))
    costs.update(dict.fromkeys("breakp callnz if ifc loop m3x3 m4x3 nrm pow rep texldd texldp lit sgn".split(), 3))
    costs.update(m3x4=4, m4x4=4, texldb=6, sincos=8)
    slots=0; counts={}
    for line in assembly.splitlines():
        line=line.split("//",1)[0].strip()
        if not line:continue
        # Native D3DDisassemble can add /* instruction-number */ prefixes.
        line=re.sub(r"^/\*.*?\*/\s*", "", line)
        tokens=line.split()
        if not tokens:continue
        op=tokens[0].split("_")[0]
        if op in {"ps", "vs", "def", "defi", "defb", "dcl", "label"}:continue
        if op not in costs:raise ValueError(f"Unknown opcode: {tokens[0]}")
        cost=3 if op=="break" and "_" in tokens[0] else costs[op]
        slots+=cost;counts[op]=counts.get(op,0)+1
    if slots>512:raise ValueError(f"{path.name}: {slots} static slots exceeds SM3 512")
    temps=[int(n) for n in re.findall(r"\br(\d+)\b",assembly)]
    if max(temps,default=-1)>=32:raise ValueError(f"{path.name}: temporary register limit")
    samplers=sorted({int(n) for n in re.findall(r"\bs(\d+)\b",assembly)})
    if samplers and max(samplers)>=(4 if target.startswith("vs") else 16):
        raise ValueError(f"{path.name}: sampler register limit")
    return {"static_instruction_slots":slots,"temporary_registers":max(temps,default=-1)+1,
            "samplers":samplers,"instructions":counts}


def main():
    source=fp.SHADERS/"world_effects.hlsl"
    before=hashlib.sha256(source.read_bytes()).hexdigest()
    env=zig_env()
    subprocess.run([str(ZIG),"c++",
                    "-target","x86-windows-gnu","-O2","-s","-static",
                    str(HERE/"compile_shaders.cpp"),"-o",str(HERE/"compile_shaders.exe")],
                   env=env,check=True)
    env.update(WINEPREFIX=str(wine_build_prefix()),WINEDEBUG="-all",
               DYLD_LIBRARY_PATH=str(WINE_ROOT/"lib/external"))
    header=["// Generated by compile_world_shaders.py; do not edit.","#pragma once","#include <windows.h>"]
    manifest={"source_sha256":before,"compiler":"Wine d3dcompiler_47 D3DCompile",
              "game_launched":False,"shaders":{}}
    for entry,target in ENTRIES:
        output=fp.COMPILED/f"{entry}.bin";asm=fp.COMPILED/f"{entry}.bin.asm"
        asm.unlink(missing_ok=True)
        subprocess.run([str(WINE_ROOT/"bin/wine"),str(HERE/"compile_shaders.exe"),
                        str(source),entry,target,str(output)],env=env,check=True,timeout=120)
        data=output.read_bytes()
        if len(data)%4:raise ValueError(f"{entry}: non-DWORD size")
        words=struct.unpack(f"<{len(data)//4}I",data)
        expected=0xfffe0300 if target.startswith("vs") else 0xffff0300
        if words[0]!=expected or words[-1]!=0xffff:raise ValueError(f"{entry}: invalid bytecode markers")
        stats=validate_assembly(asm,target)
        rows=["    "+", ".join(f"0x{w:08x}" for w in words[i:i+8])+"," for i in range(0,len(words),8)]
        header.append(f"static const DWORD k{entry}Shader[] = {{\n"+"\n".join(rows)+"\n};")
        manifest["shaders"][entry]={"target":target,"bytes":len(data),
            "sha256":hashlib.sha256(data).hexdigest(),**stats}
        print(f"Validated {entry}: {stats['static_instruction_slots']} slots, {stats['temporary_registers']} temps",flush=True)
    if hashlib.sha256(source.read_bytes()).hexdigest()!=before:raise RuntimeError("HLSL changed while compiling")
    (fp.GENERATED/"world_compiled_shaders.h").write_text("\n\n".join(header)+"\n")
    (fp.SHADERS/"world-shader-build.json").write_text(json.dumps(manifest,indent=2)+"\n")
    print("Published world_compiled_shaders.h and world-shader-build.json")

if __name__=="__main__":main()
