#!/usr/bin/env python3
"""Rebuild embedded ps_3_0 shaders; runs only our offline compiler in Wine."""
from pathlib import Path
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
sys.path[:0] = [str(Path(__file__).resolve().parents[2]), str(Path(__file__).resolve().parents[1])]  # repo root, scripts/
import northlight_paths as fp  # noqa: E402
from build_environment import wine_build_prefix, zig_env, TOOLS, WINE_ROOT, ZIG

HERE = Path(__file__).resolve().parent   # compile_shaders.cpp and the built compile_shaders.exe


def validate_assembly(path, slot_limit=512, register_limit=32):
    """Use Microsoft's ps_3_0 slot accounting, restricted to our 2D shaders.

    https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx9-graphics-reference-asm-ps-instructions-ps-3-0
    Wine's compiler does not enforce the baseline 512 static slot budget.
    """
    assembly = path.read_text()
    slots = 0
    counts = {}
    costs = dict.fromkeys("abs add break cmp dp3 dp4 else endif exp frc log mad max min mov mul nop rcp ret rsq setp sub texld".split(), 1)
    costs.update(dict.fromkeys("call crs dp2add dsx dsy endloop endrep lrp m3x2 texkill texldl".split(), 2))
    costs.update(dict.fromkeys("breakp callnz if loop m3x3 m4x3 nrm pow rep texldd texldp".split(), 3))
    costs.update(m3x4=4, m4x4=4, texldb=6, sincos=8)
    for line in assembly.splitlines():
        tokens = line.strip().split()
        if not tokens:
            continue
        op = tokens[0].split("_")[0]
        if op in {"ps", "def", "defi", "defb", "dcl", "label"}:
            continue
        if op not in costs:
            raise ValueError(f"Unknown disassembled opcode {tokens[0]}")
        cost = 3 if op == "break" and "_" in tokens[0] else costs[op]
        slots += cost
        counts[op] = counts.get(op, 0) + 1
    assert slots <= slot_limit, f"{path.name}: {slots} static instruction slots exceeds the limit {slot_limit}"
    registers = [int(n) for n in re.findall(r"\br(\d+)\b", assembly)]
    assert max(registers, default=0) < register_limit, f"{path.name}: temporary register limit exceeded"
    return {"static_instruction_slots": slots, "temporary_registers": max(registers, default=-1) + 1,
            "instructions": counts}


def main():
    env = zig_env()
    subprocess.run([
        str(ZIG), "c++",
        "-target", "x86-windows-gnu", "-O2", "-s", "-static",
        str(HERE / "compile_shaders.cpp"), "-o", str(HERE / "compile_shaders.exe"),
    ], env=env, check=True)
    env.update(WINEPREFIX=str(wine_build_prefix()), WINEDEBUG="-all",
               DYLD_LIBRARY_PATH=str(WINE_ROOT / "lib/external"))
    # No game executable, game DLL, rendering device, or existing Wine prefix is used.
    chunks = ["// Generated by compile_shaders.py; do not edit.\n#pragma once\n#include <windows.h>\n"]
    manifest = {"source_sha256": hashlib.sha256((fp.SHADERS / "effects.hlsl").read_bytes()).hexdigest(),
                "rain_source_sha256": hashlib.sha256((fp.SHADERS / "rain_mask.hlsl").read_bytes()).hexdigest(),
                "target": "ps_3_0", "shaders": {}}
    # 0.3.202 (rain mask MRT): the two rain mask pixel shaders (0.3.203: and the six particle mask ones) are ps_2_0 (they pair with the game's fixed-function vertex pipeline and write
    # oC1); their manifest entries carry their own "target" and they compile from rain_mask.hlsl. The ps_3_0 entries are unchanged.
    for entry, symbol, target in (("AO", "kAoShader", "ps_3_0"), ("AOContactBloom", "kAoContactBloomShader", "ps_3_0"), ("ContactBloom", "kContactBloomShader", "ps_3_0"),
                                  ("AOBlur", "kAoBlurShader", "ps_3_0"), ("Composite", "kCompositeShader", "ps_3_0"),
                                  ("RainMaskMRT", "kRainMaskMrtShader", "ps_2_0"), ("RainScrub", "kRainScrubShader", "ps_2_0"),
                                  ("ParticleOver1", "kParticleOver1Shader", "ps_2_0"), ("ParticleOver2", "kParticleOver2Shader", "ps_2_0"),
                                  ("ParticleAddA1", "kParticleAddA1Shader", "ps_2_0"), ("ParticleAddA2", "kParticleAddA2Shader", "ps_2_0"),
                                  ("ParticleAddC1", "kParticleAddC1Shader", "ps_2_0"), ("ParticleAddC2", "kParticleAddC2Shader", "ps_2_0"),
                                  ("ParticleMod1", "kParticleMod1Shader", "ps_2_0"), ("ParticleMod2", "kParticleMod2Shader", "ps_2_0")):
        output = fp.COMPILED / f"{entry}.bin"
        assembly = fp.COMPILED / f"{entry}.bin.asm"
        assembly.unlink(missing_ok=True)
        subprocess.run([
            str(WINE_ROOT / "bin/wine"), str(HERE / "compile_shaders.exe"),
            str(fp.SHADERS / ("effects.hlsl" if target == "ps_3_0" else "rain_mask.hlsl")), entry, target, str(output),
        ], env=env, check=True, timeout=120)
        data = output.read_bytes()
        assert len(data) % 4 == 0, f"{entry}: non-DWORD shader length"
        words = struct.unpack(f"<{len(data)//4}I", data)
        assert words[0] == (0xFFFF0300 if target == "ps_3_0" else 0xFFFF0200), f"{entry}: expected pixel shader {target}"
        assert words[-1] == 0x0000FFFF, f"{entry}: missing END instruction"
        lines = ["    " + ", ".join(f"0x{w:08x}" for w in words[i:i+8]) + ","
                 for i in range(0, len(words), 8)]
        chunks.append(f"static const DWORD {symbol}[] = {{\n" + "\n".join(lines) + "\n};\n")
        legacy = target == "ps_3_0"
        manifest["shaders"][entry] = {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
                                      **({} if legacy else {"target": target}),
                                      **(validate_assembly(assembly) if legacy else validate_assembly(assembly, 96, 12))}
    (fp.GENERATED / "compiled_shaders.h").write_text("\n".join(chunks))
    (fp.SHADERS / "shader-build.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
